### ISSUE TITLE
Unable to publish config

### ISSUE THREAD

**Issue by JoeDawson** [stevebauman/location#10]
Hey!

I'm attempting to publish the config file, but I'm having issues.

```
php artisan vendor:publish --provider=Stevebauman\Location\LocationServiceProvider --tag=config
```

Returns...

```
Can't locate path: </Volumes/joe/regency-management/vendor/stevebauman/location/src/Stevebauman/Location../../../config/config.php>
```

I also tried to copy the config to `config/location.php` and it doesn't appear to read any of my configuration options. Any ideas?

Thanks in advance!

**Comment by JoeDawson** [comment]
I had a typo in my `location.php`, so I'm not getting the missing driver issue any more.

But when setting `localhost_testing` to `false`, it still defaults to the default IP? Even with clearing the applications cache etc.

Using L5 if this helps by the way, should have mentioned that above.

**Comment by stevebauman** [comment]
Hi, that's odd. I just tried the installation and publishing on a clean L5 install and ran that command just fine (as well as `artisan vendor:publish` and that worked as well). I also tried setting the `localhost_testing` to false and it works as expected?

For your second issue mentioned however, are you using the `file` session driver?

**Comment by JoeDawson** [comment]
Thanks for your reply @stevebauman.

Indeed it is, manually creating the file isn't much of an issue though. More of a heads up just in case it was affecting others really.

I am indeed using the `file` driver for sessions.

**Comment by stevebauman** [comment]
Thanks for the quick reply @JoeDawson, try using any other session driver due the issues with the file driver mentioned here: https://github.com/laravel/framework/issues/8244. Once you do make sure you clear your route cache and other caches and see if you still have the issue.

Thanks!

**Comment by JoeDawson** [comment]
Thanks buddy, just on lunch at the mo. Will update later this afternoon when I've investigated.

**Comment by JoeDawson** [comment]
Just went back to investigate the problem I had earlier today, no longer occurs. Probably just a cacheing issue my end. Thanks!

**Comment by stevebauman** [comment]
Great to hear! Thanks for following up, appreciate it!
