### ISSUE TITLE
message: "Undefined type 'Stevebauman\\Location\\Facades\\Location'."

### ISSUE THREAD

**Issue by Tam3000** [stevebauman/location#104]
Hi,

When I try to make a call to Location in my controller, I always get this error message.

I have added the ServiceProvider and the Alias in my App.php file and I have followed all the steps. Any suggestions or usage example?

Thanks in advance

**Comment by stevebauman** [comment]
Hi @Tam3000,

You must import the `Location` facade:

```php
use Stevebauman\Location\Facades\Location;

Location::get();
```
