### ISSUE TITLE
Call to undefined method GeoIp2\Record\Location::get()

### ISSUE THREAD

**Issue by sonsoixam** [stevebauman/location#105]
namespace App\Http\Controllers;

 

use GeoIp2\Record\Location;

use Illuminate\Http\Request;

use App\Traits\ValidateTrait;

 

class TestController extends Controller

{

    use ValidateTrait;

 

    public function index(Request $request)

    {

        $ip = request()->ip();

        $position = Location::get($ip);

        return $position;

    }

}

**Comment by stevebauman** [comment]
Hi @sonsoixam,

You must import the `Location` facade:

```php
use Stevebauman\Location\Facades\Location;

Location::get();
```
