### ISSUE TITLE
Call to undefined function Stevebauman\Location\Drivers\curl_init()

### ISSUE THREAD

**Issue by engradnanalipakchamp** [stevebauman/location#114]
I used stevebauman/location it is working well offline but when I upload my project to cpanel it is giving the above error, I can't figure out what's the issue behind this issue. kindly help me to solve this issue.

**Comment by stevebauman** [comment]
Hi @engradnanalipakchamp,

This means PHP does not have the `curl` extension enabled. Enable it in your `php.ini` file on the server running cpanel.

https://stackoverflow.com/questions/6382539/call-to-undefined-function-curl-init
