### ISSUE TITLE
false on locallhost

### ISSUE THREAD

**Issue by felixkaleke** [stevebauman/location#127]
Am getting false on localhost , what might be the issue here

**Comment by ignacio-dev** [comment]
Me too. Does it just happen on localhost, or will it happen on production too?

**Comment by stevebauman** [comment]
Make sure you have testing enabled if you're working locally, otherwise all location drivers will return no data, because your web-server will be running from a 127.0.0.1 address:

https://github.com/stevebauman/location/blob/e2d38d0531f6182c647bd49cc674982a437194a9/config/location.php#L167-L173
