### ISSUE TITLE
DriverDoesNotExistException

### ISSUE THREAD

**Issue by liviuzachin** [stevebauman/location#13]
I'm using Laravel 5 and I get this:

DriverDoesNotExistException in Location.php line 492:
The driver: , does not exist. Please check the docs and verify that it does.

**Comment by stevebauman** [comment]
Have you published the config file?

**Comment by Snakox** [comment]
NoDriverAvailableException in Location.php line 339:
No Location drivers are available. Did you forget to set up your MaxMind GeoLite2-City.mmdb?

**Comment by BertKUL** [comment]
You might have updated the package without changing your config file. Delete or rename your current config file location.php and republish with "php artisan vendor:publish".

**Comment by liviuzachin** [comment]
Thanks a lot for your answers. The problem was somewhere else... some artisan errors and the package wasn't getting published.
