### ISSUE TITLE
Increasing the accuracy of latitude and longitude For Default Driver

### ISSUE THREAD

**Issue by chandachewe10** [stevebauman/location#131]
So the precision for the latitude when using the default driver is up to 4 decimal places (an accuracy of about 11 meters) so if two objects are within the 10 meters yard and you want to find the difference in distance between them it will always give 0 as the precision will depend on the firth decimal place which is neither here nor there (Not so accuracy).  Worse for the longitude as it has an accuracy of 3 decimal places.
Is it possible to increase the coordinate say to 7 decimal places. Six (7) decimal places precision in coordinates using decimal degrees notation is at a 1 cm (or 0.01 meters) resolution which will help in measuring the distance between two objects which are very close to each other or within the 10 meters yard.

**Comment by stevebauman** [comment]
Hi @chandachewe10,

The accuracy and decimal places of longitude and latitude are not provided by the code in this package.  Whatever a location driver returns is what is set on the `Position` object.

Hope this helps! 👍
