### ISSUE TITLE
Laravel10 yet?

### ISSUE THREAD

**Issue by JunichiroNakashima** [stevebauman/location#134]
Your composer.json does not include illuminate/support 10 and
I can not include your code into my laravel10 project.
Could you please check if your package is upgradable to laravel10.

**Comment by stevebauman** [comment]
Hi @JunichiroNakashima,

I’ll have this updated in a couple hours.

Thanks!

👍

**Comment by stevebauman** [comment]
Apologies for the wait! I've just release [v6.6.1](https://github.com/stevebauman/location/releases/tag/v6.6.1) with Laravel 10 support.
