### ISSUE TITLE
Any chance of separating the branch for Laravel 5.

### ISSUE THREAD

**Issue by crynobone** [stevebauman/location#14]
I'm facing an issue with `Stevebauman\Location\Location` depending on a hard coded dependency to `Illuminate\Config\Repository`, instead of `Illuminate\Contracts\Config\Repository`. This disallow any config implementation other than the default to be used including Orchestra Platform. 

If that not possible, alternatively moving some of the stuff to a `trait` would help as I can build an alternative `Location` class without having to duplicate most of the code.

**Comment by stevebauman** [comment]
That's true, I'll fix this, along with other tweaks tomorrow morning (8am EST).

**Comment by stevebauman** [comment]
Ok `v1.2.0` just released, config and session are taken from IoC so they can be swapped easily. Let me know if you encounter any issues!
