### ISSUE TITLE
Incorrect Results

### ISSUE THREAD

**Issue by amybethg** [stevebauman/location#145]
I am using this with Laravel. The location of my IP is Omaha NE but when I do a Location::get($ip) it returns Denver CO. I'm not feeling very confident right now.

**Comment by stevebauman** [comment]
Hi @amybethg,

Unfortunately there isn't anything we can do for improving results besides trying different drivers. I would try using the MaxMind driver with the latest copy of their database and seeing what results you get there.

**Comment by amybethg** [comment]
MaxMind has the correct location.

**Comment by amybethg** [comment]
@stevebauman  MaxMind has the correct data.
