### ISSUE TITLE
AWS Cloudfront driver utilizing `CloudFront-Viewer-Country` header

### ISSUE THREAD

**Issue by tobimori** [stevebauman/location#146]
[More info](https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/adding-cloudfront-headers.html)

**Comment by stevebauman** [comment]
Not sure what to do with this information.

**Comment by tobimori** [comment]
This is a feature request for a driver similiar to the Cloudflare one

**Comment by stevebauman** [comment]
Ok, I'd accept a PR if you're willing to create a driver! I'm swamped at the moment and I also personally wouldn't have any use for it.

**Comment by tobimori** [comment]
Yeah, it's on my list for a project where we use the package.
