### ISSUE TITLE
Can't run php artisan location:update

### ISSUE THREAD

**Issue by jobasc0** [stevebauman/location#151]
Hi, just downloaded the package but i can't run php artisan location:update
i am getting.

 ErrorException 

  fopen(https://download.maxmind.com/app/geoip_download?edition_id=GeoLite2-City&license_key=xUvjUr&suffix&suffix=tar.gz): Failed to open stream: HTTP request failed! HTTP/1.1 400 Bad Request

**Comment by carlosvaldesweb** [comment]
Same

**Comment by stevebauman** [comment]
Hi @jobasc0,

Did you alter the download URL in your published `config/location.php` file? `suffix` exists twice. Visiting the URL provides an `invalid suffix` error, then fixing that provides an `invalid license key` error.

Please try deleting, then re-publishing the config file, then re-run `location:update`.
