### ISSUE TITLE
False is return when I run the Location::get() with any ip address

### ISSUE THREAD

**Issue by techsolutionsuts** [stevebauman/location#152]
Hi, I tested the package about a month ago and all seems okay, today am using it in another application but I keep getting false when I run the Location::get() with any IP address and to my surprise the live version of the other application in production is also getting the same results.
I need help.
        $ipgeo_loc_stev = json_encode(\Location::get(""), true); OR
        $ipgeo_loc_stev = json_encode(\Location::get(""));

Thank you

**Comment by stevebauman** [comment]
Hi @techsolutionsuts,

Does this occur with the MaxMind driver as well? Let me know and I will re-open this issue, thanks!
