### ISSUE TITLE
What about Country Currency and Exchange Rate?

### ISSUE THREAD

**Issue by blpraveen** [stevebauman/location#156]
Can I get Country Currency and exchange rate from IP Address?

**Comment by stevebauman** [comment]
Hi @blpraveen,

Only `currencyCode` is supported:

https://github.com/stevebauman/location/blob/bd6d1c3929a9b587cdd3a22b8c9955269f653859/src/Position.php#L28

As far as I know, the current exchange rate isn't returned in any of these providers.
