### ISSUE TITLE
IP Pro driver doesn't return currency

### ISSUE THREAD

**Issue by robdekort** [stevebauman/location#164]
Thank you for this awesome package. For a commercial client I just switched to IP API Pro. However, it seems this driver doesn't return all fields. For example: the currency field is null by default when using

When I update `IpApiPro.php` driver to the following, the expected fields are returned: 

```php
<?php

namespace Stevebauman\Location\Drivers;

class IpApiPro extends IpApi
{
    /**
     * {@inheritDoc}
     */
    public function url(string $ip): string
    {
        $key = config('location.ip_api.token');

        return "https://pro.ip-api.com/json/$ip?key=$key&fields=status,message,country,countryCode,region,regionName,city,zip,lat,lon,timezone,currency,isp,org,as,query";
    }
}
```

Do you welcome a PR for this?

**Comment by stevebauman** [comment]
Hi @robdekort,

Thanks for your kind words! Yes absolutely -- send a PR and I can have it merged and released 🙏

**Comment by robdekort** [comment]
Oh love it, thanks, just submitted a PR that should fix this.
