### ISSUE TITLE
Directory separator conflicts with PharData file path

### ISSUE THREAD

**Issue by KurlenkovEvgeniy** [stevebauman/location#168]
PharData has FilesystemIterator::UNIX_PATHS flag as default in constructor (https://www.php.net/manual/en/phardata.construct.php, https://www.php.net/manual/en/class.filesystemiterator.php#filesystemiterator.constants.unix-paths).
However, ‎DIRECTORY_SEPARATOR is used in https://github.com/stevebauman/location/blob/c95c397bf54a109f9cdb335377887047408dc8bc/src/Drivers/MaxMind.php#L45 which fails to retrieve valid $relativePath on Windows.

**Comment by KurlenkovEvgeniy** [comment]
And maybe it is possible to extract file exact to $this->getDatabasePath()?
https://github.com/stevebauman/location/blob/c95c397bf54a109f9cdb335377887047408dc8bc/src/Drivers/MaxMind.php#L49
It leaves extracted junk files.

**Comment by stevebauman** [comment]
Hi @KurlenkovEvgeniy,

What do you suggest? Should we create `new PharData` with unix-paths disabled for Windows systems?

**Comment by KurlenkovEvgeniy** [comment]
Since the FilesystemIterator::UNIX_PATHS flag used in PharData, changing DIRECTORY_SEPARATOR to '/' in
https://github.com/stevebauman/location/blob/c95c397bf54a109f9cdb335377887047408dc8bc/src/Drivers/MaxMind.php#L45
 should be enough.

**Comment by KurlenkovEvgeniy** [comment]
What can you say about junk files?
There is a directory in downloading .tar.gz file. The structure is like this - maxmind.tar.gz/GeoLite2-Country_20240503/GeoLite2-Country.mmdb
After extracting, directory
%root directory from config('location.maxmind.local.path')%/GeoLite2-Country_20240503/GeoLite2-Country.mmdb
is not being deleted.
Looks like we can't extract files within directories without latter themselves.
I can suggest to clear those temp directories.
From line
https://github.com/stevebauman/location/blob/c95c397bf54a109f9cdb335377887047408dc8bc/src/Drivers/MaxMind.php#L44
```php
$relativePath = implode('/', [
    $tmpDirectory = Str::afterLast($file->getPath(), '/'), // add var and unix-separator
    $file->getFilename(),
]);
if ($tmpDirectory == $tar) { // check if in the future the .mmdb file will be in the root of archive
    $tmpDirectory = 'tmp';
}

$archive->extractTo($storage->path('/'), $relativePath, true);

file_put_contents(
    $this->getDatabasePath(),
    fopen($storage->path($relativePath), 'r')
);

$storage->deleteDirectory($tmpDirectory); // delete dir and it's files
$storage->delete($tar);
```

**Comment by 3likayed** [comment]
Solved in the latest release 
[v7.3.2](https://github.com/stevebauman/location/releases/tag/v7.3.2)
