### ISSUE TITLE
Don't report exception when location not found - Maxmind driver

### ISSUE THREAD

**Issue by veronikaValentii** [stevebauman/location#183]
when we use driver maxmind and ip not found in location file - we have large error log with stack trace (screen 1)

![Знімок екрана 2024-10-25 о 10 06 48](https://github.com/user-attachments/assets/21224ad7-c76e-41c9-a459-ee7780c117f7)

it works in this way, because when we call **rescue** function, not pass parameter **report**  on false (screen 2)

![Знімок екрана 2024-10-25 о 10 13 37](https://github.com/user-attachments/assets/efe1a040-6dac-40e1-a656-192180b7d349)

but when we use other drivers and location not found by ip - we have result false and no error log, because parameter **report**  passed (screen 3)

![Знімок екрана 2024-10-25 о 10 02 34](https://github.com/user-attachments/assets/455ee226-4b3d-41f9-8cfd-a7d2d7d3993c)

can you handle not find location for maxmind driver on the same way as other drivers and not show error log?

Thanks for any help!

**Comment by stevebauman** [comment]
Fixed in [v7.3.3](https://github.com/stevebauman/location/releases/tag/v7.3.3). Thanks for the report! 👍
