### ISSUE TITLE
NoDriverAvailableException

### ISSUE THREAD

**Issue by Snakox** [stevebauman/location#22]
Hello,

NoDriverAvailableException in Location.php line 339:
No Location drivers are available. Did you forget to set up your MaxMind GeoLite2-City.mmdb?

your plugin works in local but not online

**Comment by stevebauman** [comment]
Did you publish the configuration file on your web host?

**Comment by Snakox** [comment]
yes

**Comment by stevebauman** [comment]
Are you allowed external `file_get_contents()` requests on your web host?
