### ISSUE TITLE
DriverDoesNotExistException

### ISSUE THREAD

**Issue by sixty8** [stevebauman/location#23]
im in Laravel 5.1 dev with MAMP PRO 

DriverDoesNotExistException
The driver: Stevebauman\Location\FreeGeoIp, does not exist. Please check the docs and verify that it does.

**Comment by JoeDawson** [comment]
Also had this issue on our production site 2 nights ago, had to comment everything out for now as was urgent to fix.

**Comment by stevebauman** [comment]
Apologies for this, new release with be out shortly.

**Comment by stevebauman** [comment]
Please update to `v1.3.0`. However please be aware that the Telize driver has been removed. Please remove it from your selected driver and fallbacks.
