### ISSUE TITLE
The automatic get location is not using public ip

### ISSUE THREAD

**Issue by spencerlim** [stevebauman/location#27]
If our machine is connected to a router or medium, then we wouldn't be able to get the right location because our client ip is 192.168.0.x. 

I'm using this line of code to get the public ip, and i was thinking am i going to the wrong direction? eg. why you're not using public ip? 

`trim(shell_exec("dig +short myip.opendns.com @resolver1.opendns.com"))`

I'm currently updated my testing ip to as follow:
` 'localhost_testing_ip' => trim(shell_exec("dig +short myip.opendns.com @resolver1.opendns.com")),`

**Comment by stevebauman** [comment]
Hi @spencerlim, apologies for the very long response.

This wasn't the intended usage of the `localhost_testing_ip`. It's meant for you to set manually in the configuration to use different IP addresses to mimic a user request coming from different location.

The option was never meant to detect the local servers external IP address.
