### ISSUE TITLE
Class 'Stevebauman\Location\src\LocationServiceProvider::class' not found

### ISSUE THREAD

**Issue by michaelsreuben** [stevebauman/location#29]
When i do composer update, I get  this 
Class 'Stevebauman\Location\src\LocationServiceProvider::class' not found
![location](https://cloud.githubusercontent.com/assets/7854637/14884772/ccfe711a-0d4f-11e6-8fe5-101954bdb69a.PNG)

**Comment by KrisBraun** [comment]
I'm getting this, too. I added to `composer.json`, did a `composer install` and the `app.php` changes, then hit this when running `php artisan vendor:publish`. Running Laravel 5.1.

**Comment by stevebauman** [comment]
Hi @michaelsreuben, apologies for the long response.

Are you still having this issue?

**Comment by s1onez** [comment]
yeap still got this issue

**Comment by stevebauman** [comment]
@s1onez did you run `composer update` after inserting `stevebauman/location` into your `composer.json` file?

Otherwise, if you inserted it into your `composer.json` file, then inserted the service provider, and then ran `composer update`, you will receive this error.

**Comment by s1onez** [comment]
thx, my fault. i override vendor at server and everything ok now.

**Comment by SouarabhSarkar** [comment]
> @s1onez did you run `composer update` after inserting `stevebauman/location` into your `composer.json` file?
> 
> Otherwise, if you inserted it into your `composer.json` file, then inserted the service provider, and then ran `composer update`, you will receive this error.

didn't get over here ? can you explain bit more easily

**Comment by SouarabhSarkar** [comment]
> When i do composer update, I get this Class 'Stevebauman\Location\src\LocationServiceProvider::class' not found ![location](https://cloud.githubusercontent.com/assets/7854637/14884772/ccfe711a-0d4f-11e6-8fe5-101954bdb69a.PNG)

i got the same issue installed once again in live server and it started to work fine
