### ISSUE TITLE
Null location values 

### ISSUE THREAD

**Issue by favoriabs** [stevebauman/location#38]
Hi...when using this package i get null values. A dump of this data shows 
IP- Address `10.138.121.5`
```
Position {#230 ▼
  +countryName: ""
  +countryCode: null
  +regionCode: ""
  +regionName: null
  +cityName: null
  +zipCode: null
  +isoCode: ""
  +postalCode: ""
  +latitude: ""
  +longitude: ""
  +metroCode: ""
  +areaCode: ""
  +driver: "Stevebauman\Location\Drivers\IpInfo"
}
```
Any reason why this is happening...Btw am using this on heroku.

**Comment by Jatapiaro** [comment]
@favoriabs Are you using a free instance on Heroku?

Once I did a project using Ruby on Rails and I required the user location using his ip. But if you're on a free instance, heroku willl not be available to retrieve the ip address. I suggest you to check about the dynos in heroku,  that could solve the problem, but of course you have to pay a fee for it.

**Comment by favoriabs** [comment]
Yeah...i figured out heroku was causing the wrong reading of values. ```$ip = $_SERVER["REMOTE_ADDR"];``` (php/laravel) helped me to actually get the user's ip. Thanks anyway @Jatapiaro
