### ISSUE TITLE
session('location')

### ISSUE THREAD

**Issue by hummingbird-dev** [stevebauman/location#39]
Thanks for the great plugin. I wanted to analyse a large list of IP's and noticed that it was not possible, because the location object is stored in the session. Only the first IP from my list was analysed and after that, the session variable was set and the "function get" always returned these stored data:
```php
public function get($ip = '')
    {
        if (session()->has($this->key)) {
            return session($this->key);
        }

        if ($location = $this->driver->get($ip ?: $this->getClientIP())) {
            // We'll store the location inside of our session                                                                                   
            // so it isn't retrieved on the next request.                                                                                       
            session([$this->key => $location]);

            return $location;
        }

        return false;
    }
```
Thus, for my purpose I simply removed that part:
```php
public function get($ip = '')
    {
        if ($location = $this->driver->get($ip ?: $this->getClientIP())) {
            return $location;
        }

        return false;
    }
```
Wouldn't it be more flexible to not store the location object in the session. If needed, this could be done easily outside the plugin and would make the plugin more flexible as e.g. needed in my case.
Thanks.

**Comment by stevebauman** [comment]
Hi @hummingbird-dev, I'll add a second argument that disables this so you can retrieve positions with no session caching, thanks for the suggestion!

**Comment by hummingbird-dev** [comment]
Thanks, good idea to provide an argument to disable / enable this functionality.

**Comment by stevebauman** [comment]
I've removed the session functionality. You will now need to cache the locations in your own application if you need them cached.

New release will be out shortly, but will be a major due to the breaking change.
