### ISSUE TITLE
How to use ?

### ISSUE THREAD

**Issue by ctf0** [stevebauman/location#4]
thanx for this package ,am kinda lost ,
how do u pass the ip to the location class ,the only way i can change the ip is if i manually added it to `localhost_testing_ip` in the config file.

i checked the `Telize` class which have a `get($ip)` so when i try `Location::get('66.102.0.0')` i get this error 
`Location field: 66.102.0.0 does not exist. Please check the docs to verify which fields are available.` am i missing somthing ?

**Comment by stevebauman** [comment]
Hey thanks for the comment. The users IP address is automatically taken (see function getClientIp) and sent to the driver so there's no need to pass in any IP address. Setting the localhost_testing_IP is only for testing individual IP addresses so you can play with actual location data while in local development.

Passing in a string into the Location::get() actually returns a property from the location class, for example, Location::get('countryCode') returns the country code of the returned location. Now that I think of it, I'm going to replace that functionality with your troubles above, so you can override the IP manually.

**Comment by ctf0** [comment]
sweet ,we can have even 2 params sent to the `Location::get($ip , $key = null)` so we have the best from both worlds :).

**Comment by stevebauman** [comment]
That's definitely a great suggestion, I'll have this implemented tonight in a 1.0.5 release, thanks!

**Comment by stevebauman** [comment]
Done, 1.0.5 is released, take a look at the updated readme for details! Thanks again for the feedback!

**Comment by ctf0** [comment]
thanx for the update ,but unfortunately its not working ,its still relaying on the ip from the config file also `'localhost_forget_location' => true,` so it should refresh with each new ip.

**Comment by stevebauman** [comment]
Ok I'll take a look

**Comment by stevebauman** [comment]
Found the issue, released v1.0.6. 76596eea95b2dde73b45f8bbd53fcad5952e36dc

The driver Telize was causing an exception if a specific field wasn't available, and would cause the location to be grabbed from a fallback, and the fallbacks weren't using the IP address specified.

**Comment by ctf0** [comment]
now its workin as it should ,thanx :+1: .
