### ISSUE TITLE
Object of class Stevebauman\Location\Position could not be converted to string

### ISSUE THREAD

**Issue by getwes** [stevebauman/location#40]
Hi there, i get this issue on Laravel 5.5, i have published the config file and and using "stevebauman/location": "^2.0"

**Comment by stevebauman** [comment]
Sounds like you're trying to convert the retrieved location to a string. A `Position` object is returned when calling `Location::get()`, and cannot be converted to a string.

Please post your usage, and I will re-open this issue.
