### ISSUE TITLE
problem in find loction

### ISSUE THREAD

**Issue by sbh96** [stevebauman/location#42]
hi, why response in without locally and testing mode return my city or other information except `countryName` and `countryCode` null value?
sometimes in several ip's work fine but I want to receive an exact user `cityName`  location

**Comment by stevebauman** [comment]
Hi @sbh96,

The driver(s) may not have the city name of the IP address you're requesting.

Unfortunately I cannot guarantee the availability of the data you require. That is up to the actual hosts of the drivers that the data is being requested from (GeoPlugin, MaxMind, IpInfo etc.).
