### ISSUE TITLE
Location not working properly

### ISSUE THREAD

**Issue by wassimhattab** [stevebauman/location#44]
Hello,
I added the package to my laravel project but it's not responding correctly it's only returning the country name. And only GeoPlugin driver is working, because if i change the driver it's always returning to geoPlugin and even if i changed the ip or added an invalid ipto below line
`
$position = Location::get('x.x.x.x');
`
it's always returning same address, a;thought the ip address is not valid .

**Comment by wassimhattab** [comment]
Now i noticed that it's stored in the session and i should delete the session to get new data

**Comment by stevebauman** [comment]
Hi @wassimhattab,

I'm going to be resolving this shortly: https://github.com/stevebauman/location/issues/39
