### ISSUE TITLE
Non-static method Stevebauman\Location\Location::get() should not be called statically

### ISSUE THREAD

**Issue by mofman** [stevebauman/location#46]
Using Laravel 5.6 & PHP 7.2 I get this error

> Non-static method Stevebauman\Location\Location::get() should not be called statically

**Comment by stevebauman** [comment]
Hi @mofman, you're not using the facade:

```php
use Stevebauman\Location\Facades\Location;

$location = Location::get();
```

**Comment by mofman** [comment]
that was it, thanks steve
