### ISSUE TITLE
controller usage

### ISSUE THREAD

**Issue by robertnicjoo** [stevebauman/location#48]
Hi,

how can i use this package in my controller?

1. I'm trying to use `FreeGeoIp` what should i add to my controller? `use ??????;`
2. How can I collect ip's of my site visitors `from all front-end pages` and store the data to have ability of checking my site performance?

**Comment by stevebauman** [comment]
Hi,

For your first question, you simply use the facade:

```php
namespace App\Http\Controllers;

use Stevebauman\Location\Facade\Location;

class LocationController extends Controller
{
    public function index()
    {
        $position = Location::get();
    }
}
```

For your second, that is completely up to you. You'd have to create a database table to store the IP address and the pages you users visit. However, that implementation is way out of scope of this package.
