### ISSUE TITLE
Return 0

### ISSUE THREAD

**Issue by usmansaif** [stevebauman/location#49]
In laravel I sue this package but it return 
Position {#405 ▼
  +countryName: ""
  +countryCode: ""
  +regionCode: ""
  +regionName: ""
  +cityName: ""
  +zipCode: ""
  +isoCode: ""
  +postalCode: ""
  +latitude: "0"
  +longitude: "0"
  +metroCode: "0"
  +areaCode: null
  +driver: "Stevebauman\Location\Drivers\FreeGeoIp"
}

please guide me

**Comment by stevebauman** [comment]
Hi, have you tried changing drivers via `config/location.php` at all to see if your data changes?

**Comment by umarpucitian** [comment]
I also have this problem Steve, all is empty

**Comment by usmansaif** [comment]
I have removed this package from my project. Because, I have short deadline, therefore, I'll be removed this package.

**Comment by iamsrikanthgopi** [comment]
In your config/location file use the driver as follows

`'driver' => Stevebauman\Location\Drivers\GeoPlugin::class,`

This works!
