### ISSUE TITLE
Local development IP defaulting to 66.102.0.0

### ISSUE THREAD

**Issue by levi-cole** [stevebauman/location#5]
I am developing an app locally and when using this the data I get back isn't correct.

I have tested this in two ways, first with automatic ip detection **eg: Location::get();** and second by manually inputing my ip **eg: Location::get('192.168.1.1');**

Every time I get this same data back:

```php
object(Stevebauman\Location\Objects\Location)[141]
  public 'countryName' => string 'United States' (length=13)
  public 'countryCode' => string 'US' (length=2)
  public 'regionCode' => string 'CA' (length=2)
  public 'regionName' => string 'California' (length=10)
  public 'cityName' => string 'Mountain View' (length=13)
  public 'zipCode' => string '' (length=0)
  public 'isoCode' => string '' (length=0)
  public 'postalCode' => string '94043' (length=5)
  public 'latitude' => float 37.4192
  public 'longitude' => float -122.0574
  public 'metroCode' => string '' (length=0)
  public 'areaCode' => string '' (length=0)
  public 'isp' => string 'Google Inc.' (length=11)
  public 'ip' => string '66.102.0.0' (length=10)
  public 'driver' => string 'Stevebauman\Location\Drivers\Telize' (length=35)
  public 'error' => boolean false
```

Any ideas?

**Comment by levi-cole** [comment]
Bearing in mind Im from **United Kingdom** not the "United States"

**Comment by stevebauman** [comment]
Have you set `localhost_testing` in the config file to false? If it's set to true it overrides manual IP input as well.

**Comment by levi-cole** [comment]
It was set as true, have now set it to false and is working as expected. I did not see this mentioned in the readme file.

**Comment by stevebauman** [comment]
That's true, apologies for that. I'll have an updated readme shortly.

**Comment by levi-cole** [comment]
Thank you for your quick response.

**Comment by stevebauman** [comment]
No problem! I've updated the readme for configuration options.

**Comment by warmwhisky** [comment]
Has this setting been removed as I cannot find it in config. I'm also getting "United States" but am in eSwatini.

`'localhost_testing ' => true,`

**Comment by warmwhisky** [comment]
Sorry I found the setting 'LOCATION_TESTING' and set to false, but it failed to detect. would it be detecting my local ip address?

If I set the test ip address to my isp ip I get the correct country.

**Comment by stevebauman** [comment]
Hi @warmwhisky, yes if you're running your server locally Laravel will detect your IP address as 127.0.0.1 (localhost), which will return no address from any of the drivers. This is the purpose of the `localhost_testing` option. 👍
