### ISSUE TITLE
cannot change the default driver

### ISSUE THREAD

**Issue by tigerjun98** [stevebauman/location#52]
/*
    |--------------------------------------------------------------------------
    | Driver
    |--------------------------------------------------------------------------
    |
    | The default driver you would like to use for location retrieval.
    |
    */

    'driver' => Stevebauman\Location\Drivers\FreeGeoIp::class,

Position {#556 ▼
  +countryName: ""
  +countryCode: "US"
  +regionCode: ""
  +regionName: ""
  +cityName: ""
  +zipCode: null
  +isoCode: ""
  +postalCode: ""
  +latitude: "37.7510"
  +longitude: "-97.8220"
  +metroCode: ""
  +areaCode: ""
  +driver: "Stevebauman\Location\Drivers\IpInfo"
}

The output driver still Ipinfo

**Comment by Eugene-Melbourne** [comment]
Same

**Comment by stevebauman** [comment]
FreeGeoIp is shutdown - if it's using a different driver that means it's failing to retrieve data from that particular driver, so it falls back to the drivers you've configured in the `fallbacks` array in your `config/locations.php` file.
