### ISSUE TITLE
How can I get regionName and regionCode?

### ISSUE THREAD

**Issue by JLanky** [stevebauman/location#54]
When I get location data, I don’t receive data with a region. How do I get the region? Thanks

Position {#922 ▼
  +countryName: "Ukraine"
  +countryCode: "UA"
  +regionCode: ""
  +regionName: ""
  +cityName: "Mykolayiv"
  +zipCode: ""
  +isoCode: ""
  +postalCode: "54046"
  +latitude: "46.9659"
  +longitude: "31.9974"
  +metroCode: ""
  +areaCode: ""
  +driver: "Stevebauman\Location\Drivers\MaxMind"
}

**Comment by JLanky** [comment]
Hello! I found the code below in this project file /vendor/stevebauman/location/src/Drivers/MaxMind.php
and thus added region_name, region_code, but I'm not sure that I can change its file.
return new Fluent([
                'country' => $record->country->name,
                'country_code' => $record->country->isoCode,
                'city' => $record->city->name,
                'region_name' => $record->region->regionName,
                'region_code' => $record->region->regionCode,
                'postal' => $record->postal->code,
                'latitude' => (string) $record->location->latitude,
                'longitude' => (string) $record->location->longitude,
                'metro_code' => (string) $record->location->metroCode,
            ]);

**Comment by stevebauman** [comment]
Hi @JLanky,

To add more data to a `Position` instance, you will have to create your own driver and your own `Position` class as shown in the readme:

https://github.com/stevebauman/location#creating-your-own-drivers
