### ISSUE TITLE
Location didn't retrieved showing empty array.

### ISSUE THREAD

**Issue by bhaswanth97** [stevebauman/location#61]
Hello,

I am using this package in one of my projects, and I must say it's an excellent package which I liked very much. It's been working fine but a small issue has been raised yesterday. When I open the project yesterday it didn't retrieve location. It showed null values to the array. I can't able to find what's the issue here, then its been working fine today. I think this might be the problem of API. can you please confirm me the issue? if it is from API, then please tell me how many requests I can send per day and if it is limited, how can I change it to unlimited.

Thanks

**Comment by jackbayliss** [comment]
@vaibhavisojitra25 Have you tried changing your driver  [here] (https://github.com/stevebauman/location/blob/master/src/Config/config.php#L14)?

It may be that you're requesting too much too quickly, or you've used your "FREE" limit on your driver. 

I would suggest reading the [maximind](https://github.com/stevebauman/location#setting-up-maxmind) option, it's probably the most viable. 👍

**Comment by stevebauman** [comment]
I've added some validation to ensure the returned driver data isn't empty as well as the hydrated position before moving to a fallback driver. This should resolve issues with some drivers returning empty JSON responses when your request limit is hit.
