### ISSUE TITLE
Support Laravel 6

### ISSUE THREAD

**Issue by jozeflambrecht** [stevebauman/location#62]
Will this awesome package be compatible with Laravel 6.*?

**Comment by stevebauman** [comment]
Hi @jozeflambrecht,

I'm definitely going to make it compatible along with some updates. Will be coming later today or tomorrow. Thanks! :smile:

**Comment by stephenlake** [comment]
Unless I'm missing something, this is already compatible, the dependency on illuminate/support should just be updated to support 6.* - Keeping an eye on this because a this is a dependency of a dependency and it's blocking our Laravel 6.0 upgrade :cry:

**Comment by stevebauman** [comment]
Done! [v4.0.0](https://github.com/stevebauman/location/releases/tag/v4.0.0) is now tagged.

Thanks for your patience!

**Comment by jozeflambrecht** [comment]
thanks!
