### ISSUE TITLE
I have purchased the pro version of IP INFO

### ISSUE THREAD

**Issue by robertwstickets** [stevebauman/location#63]
Where do I configure it for a pro account. I see where you have the URLS but where do I place the token... Looks like your trying to grab the token from the .env file?

**Comment by robertwstickets** [comment]
Just an FYI unsure if you know or not.. Composer is not grabbing the newest update you have done.

**Comment by stevebauman** [comment]
Just released [v5.0.0](https://github.com/stevebauman/location/releases/tag/v5.0.0), thanks for the reminder!

**Comment by robertwstickets** [comment]
No worries. Thanks again Steve! And Thanks for making this awesome integration for IP Location

**Comment by stevebauman** [comment]
No problem @robertwstickets! I'm glad you enjoy using this package!
