### ISSUE TITLE
Installation errors on Laravel 6.4.0

### ISSUE THREAD

**Issue by p19lord** [stevebauman/location#64]
HI
I try to install this on Laravel 6.4.0 and I get this error:

> `Using version ^5.0 for stevebauman/location
> ./composer.json has been updated
> Loading composer repositories with package information
> Updating dependencies (including require-dev)
> Your requirements could not be resolved to an installable set of packages.
> 
>   Problem 1
>     - laravel/framework 5.0.x-dev requires ext-mcrypt * -> the requested PHP extension mcrypt is missing from your system.
>     - Conclusion: don't install hisorange/browser-detect 3.1.4
>     - Conclusion: don't install hisorange/browser-detect 3.1.3
>     - Conclusion: don't install hisorange/browser-detect 3.1.2
>     - Conclusion: don't install hisorange/browser-detect 3.1.1
>     - Conclusion: remove laravel/framework v6.4.0
>     - Installation request for hisorange/browser-detect ^3.1 -> satisfiable by hisorange/browser-detect[3.1.0, 3.1.1, 3.1.2, 3.1.3, 3.1.4].
>     - Conclusion: don't install laravel/framework v6.4.0
>     - hisorange/browser-detect 3.1.0 requires laravel/framework ~5.0 -> satisfiable by laravel/framework[5.0.x-dev, 5.1.x-dev, 5.2.x-dev, 5.3.x-dev, 5.4.x-dev, 5.5.x-dev, 5.6.x-dev, 5.7.x-dev, 5.8.x-dev].
>     - Can only install one of: laravel/framework[5.5.x-dev, v6.4.0].
>     - Can only install one of: laravel/framework[5.6.x-dev, v6.4.0].
>     - Can only install one of: laravel/framework[5.7.x-dev, v6.4.0].
>     - Can only install one of: laravel/framework[5.8.x-dev, v6.4.0].
>     - Can only install one of: laravel/framework[5.1.x-dev, v6.4.0].
>     - Can only install one of: laravel/framework[5.2.x-dev, v6.4.0].
>     - Can only install one of: laravel/framework[5.3.x-dev, v6.4.0].
>     - Can only install one of: laravel/framework[5.4.x-dev, v6.4.0].
>     - Installation request for laravel/framework (locked at v6.4.0, required as ^6.2) -> satisfiable by laravel/framework[v6.4.0].
> 
>   To enable extensions, verify that they are enabled in your .ini files:
>     - C:\xampp\php\php.ini
>   You can also run `php --ini` inside terminal to see which files are used by PHP in CLI mode.
> 
> Installation failed, reverting ./composer.json to its original content.`

As far as I dug in there is no mrcrypt extension in PHP 7.3.10 or any PHP 7 versions.

does anyone have any idea to solve this?

**Comment by tvercruysse** [comment]
@p19lord please check if you can find `mcrypt`, and not `mrcrypt`

**Comment by stevebauman** [comment]
Hi @p19lord, can you post your whole `composer.json` file?
