### ISSUE TITLE
MaxMind database fetching requires registering for an account

### ISSUE THREAD

**Issue by lptn** [stevebauman/location#66]
https://blog.maxmind.com/2019/12/18/significant-changes-to-accessing-and-using-geolite2-databases/

New reqs:
 1. Provide MAXMIND_LICENSE_KEY
 2. Result file .tar.gz (instead of .gz)

**Comment by stevebauman** [comment]
Hi @lptn,

Would you mind submitting a PR to fix this? I won't be able to resolve for a couple days / weeks unfortunately.

**Comment by lptn** [comment]
@stevebauman 
Sorry, I use another package where this problem is fixed and currently don't have a time to fix this problem in this package

**Comment by stevebauman** [comment]
Ok -- would you mind linking that alternate package where this is fixed so that I have a reference point and can resolve it here for future developers?

**Comment by lptn** [comment]
we use  https://github.com/Torann/laravel-geoip

**Comment by stevebauman** [comment]
Thank you @lptn! Much appreciated 👍

**Comment by stevebauman** [comment]
Hmm -- this isn't broken at all. I've followed the steps directly in the readme and it works as expected. You simply need to register now to download the database, instead of being able to download it as a guest.
