### ISSUE TITLE
Class 'Illuminate\Foundation\Auth\Location' not found

### ISSUE THREAD

**Issue by Senpaiproductions** [stevebauman/location#67]
Laravel auth can't resolve the Location facade in 'AuthenticatesUsers.php'
    
protected function authenticated(Request $request, $user)
    {
        $user->update([
            'last_login_at' => Carbon::now()->toDateTimeString(),
            'last_login_ip' => $request->getClientIp(),
            'country' => Location::get($request->getClientIp())
        ]);
    }

**Comment by stevebauman** [comment]
Hi @Senpaiproductions,

You must import the facade or use a backslash to indicate the root namespace:

```php
use Stevebauman\Location\Facades\Location;
```
