### ISSUE TITLE
Location::get(); return data, but not for Location::get('192.168.1.1'); always return false

### ISSUE THREAD

**Issue by zihad15** [stevebauman/location#68]
Hi stevebauman I have some question why $position = Location::get(); return some data but if I change to $position = Location::get('192.168.1.1'); always return false, and I've tried many unique ip for testing but the result still same, Thanks for answer

**Comment by robertwstickets** [comment]
@zihad15 192.168.0/24 Subnets are local only. This means that 192.168.1.1 is your Local Router IP address most likely. There is no location associated with these types of IP Addresses. The same goes for 10.0.0/24

**Comment by stevebauman** [comment]
Thanks for the thorough explanation @robertwstickets!
