### ISSUE TITLE
` Symfony\Component\Debug\Exception\FatalThrowableError  : Class 'Stevebauman\Location\LocationServiceProvider' not found

### ISSUE THREAD

**Issue by codaru** [stevebauman/location#75]
Getting the following error with this and laravel when I push to production. When I remove this dependency, app runs fine. Thoughts?

` Symfony\Component\Debug\Exception\FatalThrowableError  : Class 'Stevebauman\Location\LocationServiceProvider' not found

  at /home/domain/laravel_app/vendor/laravel/framework/src/Illuminate/Foundation/Application.php:671
* @return \Illuminate\Support\ServiceProvider
 */
public function resolveProvider($provider)
 {
  return new $provider($this);
}
 
/**
* Mark the given provider as registered.
`

**Comment by jackbayliss** [comment]
@codaru  Have you tried a `composer dump-autoload`? I presume you've already done a `composer install`?

**Comment by codaru** [comment]
> @codaru Have you tried a `composer dump-autoload`? I presume you've already done a `composer install`?

Yes I have. I am going to close this issue for now while I try to debug if further. I feel confident about having ruled out issues on my end re: composer and implementation, but will dig into it further by staging it elsewhere. Will report back in the event there is an update.

**Comment by niilante** [comment]
I resolved mine with these commands in order as they appear

1. `composer dump-autoload`
2. `php artisan clear-compiled`
3. ` php artisan config:cache`
