### ISSUE TITLE
Artisan Publish on Laravel 5: Can't locate path

### ISSUE THREAD

**Issue by Sennik** [stevebauman/location#8]
**php artisan vendor:publish is failing with:**
Can't locate path: /var/www/domain.com/vendor/stevebauman/location/src/../../config/config.php

**Comment by stevebauman** [comment]
Sorry about this. Made package PSR-2 and PSR-4 compatible and didn't change the configuration path inside the service provider. Will be fixed shortly! Thanks!

**Comment by stevebauman** [comment]
Should be fixed now, run `composer update`, thanks!
