### ISSUE TITLE
not getting supported for laravel 8

### ISSUE THREAD

**Issue by Jupeen** [stevebauman/location#84]
getting this error  
Problem 1
    - Installation request for stevebauman/location ^5.1 -> satisfiable by stevebauman/location[v5.1.0].
    - Conclusion: remove laravel/framework v8.1.0
    - Conclusion: don't install laravel/framework v8.1.0
    - stevebauman/location v5.1.0 requires illuminate/support ~5.0|~6.0|~7.0 -> satisfiable by illuminate/support[

**Comment by stevebauman** [comment]
Hi there, sorry for the wait on this! I've just released [v5.2.0](https://github.com/stevebauman/location/releases/tag/v5.2.0) with Laravel 8.0 support. 👍
