### ISSUE TITLE
Location::get($ip); always returning same location coordinates

### ISSUE THREAD

**Issue by Spepardy** [stevebauman/location#86]
I executed Location::get($ip) several times with different IP addresses of different devices at different/distant locations expecting to receive different location coordinates, but I received same longitude and latitude coordinates for all the IPs. How then can I determine the different locations of users please?
Please help.
Thank you

**Comment by bmbBAMBUS** [comment]
Set environment variable
` LOCATION_TESTING=false`

**Comment by Spepardy** [comment]
Wow, problem solved successfully.
Thank you very much.

**Comment by stevebauman** [comment]
@bmbBAMBUS Thank you so much for taking the time to assist someone on my repository, I really appreciate it! ❤️ 

@Spepardy I’m glad you’re up and running!

**Comment by bmbBAMBUS** [comment]
@stevebauman I've also received a lot of help in my programming career, so I'm trying to pay it back.

Good package btw :+1:
