### ISSUE TITLE
Non static method 'get' should not be called statically

### ISSUE THREAD

**Issue by obink** [stevebauman/location#87]
- Laravel 7
- PHP 7.3.12
- finished setting up the config and also I put an aliases  'Location' => 'Stevebauman\Location\Facades\Location',
- published vendor

in my controller

`use Stevebauman\Location\Location;
`
```
 public function show($product)
    {
        $product = Product::find($product);
        views($product)->record();

        $images = $product->images;

        $whoIsIp = request()->ip();

        $position = Location::get($whoIsIp);
        dd($position);

        $dbLatestView = DB::table('views')->orderBy('id', 'DESC')->where('viewable_id', $product->id)->limit(1);
        $dbLatestView->update(['ip_address'=>$whoIsIp] );

        return view('product', compact('product', 'images'));
}
```

and I'm getting this kind of error

**ErrorException
Non-static method Stevebauman\Location\Location::get() should not be called statically
http://127.0.0.1:8000/catalogue/2**

**Comment by edmondsylar** [comment]
don't import it with 
**_use Stevebauman\Location\Location;_**

comment out this line and run your code again, its sort of declared globally

**Comment by stevebauman** [comment]
Hi there!

You must use the **facade**:

```php
use Stevebauman\Location\Facades\Location;
```

**Not**:

```php
use Stevebauman\Location\Location;
```

Hope this helps!

**Comment by obink** [comment]
the mistake I made was, I used a static local IP. And it works now with facades, sorry for the late reply. thanks.
