### ISSUE TITLE
The location driver 

### ISSUE THREAD

**Issue by baraaofficial** [stevebauman/location#89]
**What is the solution to this problem the location driver ??**

**Comment by stevebauman** [comment]
Hi @baraaofficial, I'm not sure what the problem is exactly -- are you getting an exception? Can you detail what you're experiencing?

I'm happy to help as soon as I get some more information 👍

**Comment by baraaofficial** [comment]
I installed your package, and then this error comes to me. "The location driver [] does not exist.
".
Do I have to be a https://ip-api.com/ user?

**Comment by stevebauman** [comment]
Have you published the `location.php` configuration file?:

```bash
php artisan vendor:publish --provider="Stevebauman\Location\LocationServiceProvider"
```

If you have published the configuration file and are still getting this error, I would then assume you may be caching your configuration files. Try re-caching using `php artisan config:cache` then try again.

I believe that should be the only reason why it would show this error.

Let me know if you still encounter this issue after attempting the above resolutions 👍

**Comment by baraaofficial** [comment]
success steve bauman 😊
Thanks

**Comment by stevebauman** [comment]
Awesome, happy to help @baraaofficial!

**Comment by ridwanmaulanaavana** [comment]
composer require stevebauman/location-cloudflare-driver im not found in github
