### ISSUE TITLE
Bump geoip2/geoip2 version

### ISSUE THREAD

**Issue by nagi1** [stevebauman/location#91]
Thanks for great package, I suggest bump geoip2/geoip2 to the latest none breaking change versions 2.11.

or update composer.json to require "^2.0".

because it preventing me to use other packages 

  Problem 1
    - stevebauman/location is locked to version v5.2.0 and an update of
    - stevebauman/location v5.2.0 requires geoip2/geoip2 2.8.* -> found
root composer.json require (^2.11).

**Comment by stevebauman** [comment]
Hi @nagi1,

Can you send a PR and I’ll merge it in and make a release? I’m not around a computer for the moment.

**Comment by nagi1** [comment]
OMG you are the best!! one PR coming right away :)  :heart:

**Comment by nagi1** [comment]
Fixed in #92

**Comment by stevebauman** [comment]
Haha thanks @nagi1, happy to help! ❤️ 

Just released v6.1.0 with your PR 👍

**Comment by nagi1** [comment]
Fastest unexpected hot fix and merge on Github :laughing: .
